apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyberchef
  labels:
    app: cyberchef
    environment: production
    team: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cyberchef
  template:
    metadata:
      labels:
        app: cyberchef
        environment: production
        team: devops
    spec:
      containers:
        - name: cyberchef
          image: ghcr.io/gchq/cyberchef:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
