replicaCount: 1

image:
  repository: ghcr.io/gchq/cyberchef
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

labels:
  app: cyberchef
  environment: production

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
