apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyberchef
  labels:
    app: cyberchef
    environment: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cyberchef
  template:
    metadata:
      labels:
        app: cyberchef
        environment: production
    spec:
      containers:
        - name: cyberchef
          image: {{ default "ghcr.io/gchq/cyberchef" .Values.imageRepository }}:{{ default "latest" .Values.imageTag }}
          imagePullPolicy: {{ default "Always" .Values.imagePullPolicy }}
          ports:
            - containerPort: 80
