apiVersion: v1
kind: Service
metadata:
  name: cyberchef
  labels:
    app: {{ .Values.labels.app }}
    environment: {{ .Values.labels.environment }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: {{ .Values.labels.app }}
    environment: {{ .Values.labels.environment }}
