apiVersion: v1
kind: Service
metadata:
  name: cyberchef
  labels:
    app: cyberchef
    environment: production
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: cyberchef
