apiVersion: v1
kind: Service
metadata:
  name: cyberchef
  labels:
    {{- include "cyberchef-helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    {{- include "cyberchef-helm-chart.selectorLabels" . | nindent 4 }}
